language: java

jdk:
 - openjdk6
 - openjdk7

before_install:
 - sudo apt-get update -y
 - sudo apt-get install build-essential uuid-dev pkg-config libtool autoconf automake -y
 - sudo apt-get install protobuf-compiler -y

 - sudo git clone https://github.com/zeromq/zeromq3-x.git
 - cd zeromq3-x
 - sudo ./autogen.sh
 - sudo ./configure
 - sudo make
 - sudo make install
 - cd ..

 - sudo git clone https://github.com/sergei-ivanov/maven-protoc-plugin.git
 - cd maven-protoc-plugin
 - sudo git checkout tags/maven-protoc-plugin-0.3.2
 - mvn -version
 - mvn install -e --quiet -DskipTests=true
 - cd ..

install: mvn clean install -e --quiet -DskipTests=true

script: mvn clean test
