language: java

jdk:
 - openjdk6
 - openjdk7

before_install:
 - sudo apt-get update -y
 - sudo apt-get install build-essential uuid-dev pkg-config libtool autoconf automake -y
 - sudo wget http://download.zeromq.org/zeromq-3.2.4.tar.gz
 - sudo wget https://github.com/zeromq/jzmq/archive/v2.2.2.tar.gz

install:
 - sudo tar -zxvf zeromq-3.2.4.tar.gz
 - cd zeromq-3.2.4
 - sudo ./autogen.sh
 - sudo ./configure
 - sudo make
 - sudo make install
 - cd ..

 - sudo tar -zxvf v2.2.2.tar.gz
 - cd jzmq-2.2.2
 - sudo ./autogen.sh
 - sudo ./configure
 - sudo make
 - sudo make install
 - mvn install -e --quiet -DskipTests=true -Dgpg.skip=true
 - cd ..

before_script:
 - mvn install -e --quiet -Ptravis-ci -DskipTests -Ptravis-ci

script:
 - mvn test -e -Ptravis-ci