language: java

jdk:
 - openjdk6
 - openjdk7

before_install:
 - sudo apt-get update -y
 - sudo apt-get install build-essential uuid-dev pkg-config libtool autoconf automake -y
 - sudo apt-get install protobuf-compiler -y

 - sudo git clone https://github.com/sergei-ivanov/maven-protoc-plugin.git
 - cd maven-protoc-plugin
 - sudo git checkout tags/maven-protoc-plugin-0.3.2
 - mvn install -DskipTests=true
 - cd ..

install: mvn clean install -DskipTests=true

script: mvn clean test
