language: java

jdk:
 - openjdk6
 - openjdk7

before_install:
 - sudo apt-get update -y
 - sudo apt-get install uuid-dev pkg-config libtool autoconf automake -y

install: mvn clean install --quiet -DskipTests=true

script: mvn clean test
